name: Dependent Jobs example
on: push
jobs:
  job2:
    runs-on: ubunntu-latest
    needs: job1
    steps:
      - name: stepA
        run: echo "Hello ate the top"
  job1:
    runs-on: ubunntu-latest
    steps:
      - name: stepB
        run: echo "Hello at the bottom"
    
  
