name: CI on multiple Events
on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build-and-test:
      runs-on: ubuntu-latest
        steps:
          - name: Echo basic information
            run:
              echo "REF: $GITHUB_REF"
          
